### ISSUE TITLE
Inventories

### ISSUE THREAD

**Issue by JSCraig** [sfu-dhil/bep#41]
Is is possible to enter the details of a single inventory listing, for example 12 different books and, using a single entry of data, identify all 12 books, or does this go against the very principle of data entry, in which each discrete entry must be treated as a single entity?  I suspect we have to do each separately. But if this is right, would it be helpful to have a field in which we can enter the number of books in the entry and which number this particular book happens to be - 1st of 12 books, 7th of 12 books and so forth.  Currently this information is going into the Notes/Description

**Comment by ubermichael** [comment]
This is definitely possible John, and something that makes quite a bit of sense. It's not an easy thing to get right so let's make sure we agree. We'll take https://dhil.lib.sfu.ca/bep/inventory/2 as an example.

The inventory has a book field, which is single valued. But that's not right because the inventory record has five books. So you entered this record five times because that's all the interface allowed you to do. Clearly the interface is wrong.

The solution is, I think, to make the Book field multivalued. Then you can associate as many books as you need in the order that you need.

**Comment by JSCraig** [comment]
Your solution would be great. Many thanks

Here's another example from Haxey.  The inventory lists 25 books and I've made 25 separate entries as you can see from the screenshots, but to be able to make the Book field multivalued will eliminate all this.  
<img width="1240" alt="Screenshot 2021-02-18 at 22 54 29" src="https://user-images.githubusercontent.com/75693581/108432644-9cd8f300-723c-11eb-8994-44facde0020f.png">

<img width="1331" alt="Screenshot 2021-02-18 at 22 54 46" src="https://user-images.githubusercontent.com/75693581/108432663-a3676a80-723c-11eb-8fe1-38ed9a813adb.png">

**Comment by JSCraig** [comment]
If we can make the Book field multivalued for Inventories, can we make it multivalued for Transactions as well. Here's an example of two books being purchased at the same time:
https://dhil.lib.sfu.ca/bep/transaction/58

**Comment by ubermichael** [comment]
Moved the request for transactions to hold multiple books to #46
